### ISSUE TITLE
How would the branch length in the tree file influence the reconstruction outputs?

### ISSUE THREAD

**Issue by JhinAir** [jkimlab/DESCHRAMBLER#19]
Hi dear Jaebum,

My question is described as in the title. I have tested the example in the code for several rounds. 
The first round was using the tree file provided by default as: ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);
The second round was run with ((spc1:0.02,spc2:0.03)@:0.04,spc3:0.05);
For the third I removed the branch length and it got error which seems expected. 

For the first and second rounds, all the outputs are the same except for the conservation score file or the adjacency score in Ancestor.ADJS. I wonder: 1) what does these conservation scores exactly means? 2) how does it affected by the branch length? 3) how should we evaluate the reconstruction results with this score? which is the better to look into, conservation or adjacency scores?
Looking forward to your help. Thank you very much!

Best regards,
Jing

**Comment by jkimlab** [comment]
Hi Jing,

The adjacency score is a probability representing the reliability of the predicted join of two synteny blocks. The probability is calculated by considering the topology and branch lengths of given species. That is, if the branch lengths are changed, the final probability can be also changed.

The adjacency score is also used to choose the most likely join of two synteny blocks when there are multiple candidates. Even though the adjacency score is changed because of the change of branch lengths, if a certain join has the highest score, it can be still chosen.

As I said, you can consider the adjacency score as the reliability of the predicted join. If it is too low, there could be candidate joins of other synteny blocks with a similar but lower score.

**Comment by JhinAir** [comment]
I see, thank you!
