### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by gepmat** [jkimlab/DESCHRAMBLER#3]
Make seems to work, but I get this error while running the main script:
"UNIVERSAL does not export anything at /home/.../DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.22/base.pm line 97."

It seems to be the main issue here, could you help me with this ?
Which version of perl did you use to run your script ?

Thanks,

Matthieu

**Comment by huangziyan11111** [comment]
I met the same problem, please help us to solve. thank you.

**Comment by jkimlab** [comment]
Thanks for using DESCHRAMBLER. The following may be the solution to your problem.

All Perl modules required for DESCHRAMBLER are in the "lib/perl” directory. If it is because of Perl module conflict, I think you can install all modules in the “lib/perl” directories in your server, and remove the line starting with “use lib …” in all Perl script files in the “script” directory.

Thanks.

**Comment by huangziyan11111** [comment]
Ok. thank you for your reply. I find the module and copy it to the cwd path, it can be solved also.



huangziyan11111@163.com
 
From: jkimlab
Date: 2019-08-26 11:46
To: jkimlab/DESCHRAMBLER
CC: huangziyan11111; Comment
Subject: Re: [jkimlab/DESCHRAMBLER] Compilation failed (#3)
Thanks for using DESCHRAMBLER. The following may be the solution to your problem.

All Perl modules required for DESCHRAMBLER are in the "lib/perl” directory. If it is because of Perl module conflict, I think you can install all modules in the “lib/perl” directories in your server, and remove the line starting with “use lib …” in all Perl script files in the “script” directory.

Thanks.
